/**
 * @file registers.h
 * @brief Special Function Register (SFR) index and bit-field constants
 *
 * @section LICENSE
 *  Copyright (C) 2009-2024 Kalray SA.
 *  All rights reserved.
 *
 * NOTE: this is a deliberately minimal subset. KVX's real registers.h is a
 * ~270KB file generated by its Machine Description System (MDS) covering
 * every SFR. Only the timer control/value/reload registers are ported
 * here so far - just enough for libgloss/lvx-mbr/timer.c.
 *
 * These specific values (SFR indices 18-22, and the TCR bit-field offsets
 * 16-21) were cross-checked against the LVX MDS's own generated tables
 * (lvx-mds/lvx-family/MDD/lvx/Register.table and RegField.table) and are
 * confirmed bit-for-bit identical to KVX's kv4-v1 - not just assumed by
 * "same ABI" policy. Port more of registers.h here as needed, ideally by
 * checking the same MDS tables rather than copying KVX's numbers blind.
 */

#ifndef _LVX_REGISTERS_H
#define _LVX_REGISTERS_H

/* SFR indices (operand to __builtin_lvx_get/set/wfxl) */
#define LVX_SFR_TCR      18  // Timer Control $tcr $s18
#define LVX_SFR_T0V      19  // Timer 0 value $t0v $s19
#define LVX_SFR_T1V      20  // Timer 1 value $t1v $s20
#define LVX_SFR_T0R      21  // Timer 0 reload value $t0r $s21
#define LVX_SFR_T1R      22  // Timer 1 reload value $t1r $s22

/* TCR bit-field offsets */
#define LVX_SFR_TCR_T0CE_SHIFT      16
#define LVX_SFR_TCR_T0CE_WIDTH      1
#define LVX_SFR_TCR_T1CE_SHIFT      17
#define LVX_SFR_TCR_T1CE_WIDTH      1
#define LVX_SFR_TCR_T0IE_SHIFT      18
#define LVX_SFR_TCR_T0IE_WIDTH      1
#define LVX_SFR_TCR_T1IE_SHIFT      19
#define LVX_SFR_TCR_T1IE_WIDTH      1
#define LVX_SFR_TCR_T0ST_SHIFT      20
#define LVX_SFR_TCR_T0ST_WIDTH      1
#define LVX_SFR_TCR_T1ST_SHIFT      21
#define LVX_SFR_TCR_T1ST_WIDTH      1

/*
 * __builtin_lvx_wfxl(sfr, mask) packs a clear-mask in the low 32 bits and
 * a set-value (pre-shifted into the same bit position + 32) in the high
 * 32 bits of its second operand - see newlib/libm/machine/lvx/fe*.c for
 * other users of this same encoding.
 */
#define LVX_SFR_TCR_T0CE_WFXL_MASK  0x10000LL
#define LVX_SFR_TCR_T0CE_WFXL_CLEAR 0x10000LL
#define LVX_SFR_TCR_T0CE_WFXL_SET   0x1000000000000LL
#define LVX_SFR_TCR_T1CE_WFXL_MASK  0x20000LL
#define LVX_SFR_TCR_T1CE_WFXL_CLEAR 0x20000LL
#define LVX_SFR_TCR_T1CE_WFXL_SET   0x2000000000000LL
#define LVX_SFR_TCR_T0IE_WFXL_MASK  0x40000LL
#define LVX_SFR_TCR_T0IE_WFXL_CLEAR 0x40000LL
#define LVX_SFR_TCR_T0IE_WFXL_SET   0x4000000000000LL
#define LVX_SFR_TCR_T1IE_WFXL_MASK  0x80000LL
#define LVX_SFR_TCR_T1IE_WFXL_CLEAR 0x80000LL
#define LVX_SFR_TCR_T1IE_WFXL_SET   0x8000000000000LL
#define LVX_SFR_TCR_T0ST_WFXL_MASK  0x100000LL
#define LVX_SFR_TCR_T0ST_WFXL_CLEAR 0x100000LL
#define LVX_SFR_TCR_T0ST_WFXL_SET   0x10000000000000LL
#define LVX_SFR_TCR_T1ST_WFXL_MASK  0x200000LL
#define LVX_SFR_TCR_T1ST_WFXL_CLEAR 0x200000LL
#define LVX_SFR_TCR_T1ST_WFXL_SET   0x20000000000000LL

#endif /* _LVX_REGISTERS_H */
