/*
 * lvx-jmpbuf.h: setjmp/longjmp register-save layout.
 *
 * Generated by MDS/BE/LIBC/BIN/libc-jmpbuf.pl from Convention-lvx-regular
 * (Convention.table). Do not edit by hand; regenerate instead. Consumed by
 * newlib's setjmp.S and gdb's lvx-common-tdep.c (get_longjmp_target).
 */

#ifndef _LVX_JMPBUF_H
#define _LVX_JMPBUF_H

#define LVX_JMPBUF_R18_OFFSET  0x00
#define LVX_JMPBUF_R19_OFFSET  0x08
#define LVX_JMPBUF_R20_OFFSET  0x10
#define LVX_JMPBUF_R21_OFFSET  0x18
#define LVX_JMPBUF_R22_OFFSET  0x20
#define LVX_JMPBUF_R23_OFFSET  0x28
#define LVX_JMPBUF_R24_OFFSET  0x30
#define LVX_JMPBUF_R25_OFFSET  0x38
#define LVX_JMPBUF_R26_OFFSET  0x40
#define LVX_JMPBUF_R27_OFFSET  0x48
#define LVX_JMPBUF_R28_OFFSET  0x50
#define LVX_JMPBUF_R29_OFFSET  0x58
#define LVX_JMPBUF_R30_OFFSET  0x60
#define LVX_JMPBUF_R31_OFFSET  0x68
#define LVX_JMPBUF_R13_OFFSET  0x70
#define LVX_JMPBUF_R14_OFFSET  0x78
#define LVX_JMPBUF_LS_OFFSET  0x80
#define LVX_JMPBUF_LE_OFFSET  0x88
#define LVX_JMPBUF_LC_OFFSET  0x90
#define LVX_JMPBUF_CS_OFFSET  0x98
#define LVX_JMPBUF_RA_OFFSET  0xa0
#define LVX_JMPBUF_R12_OFFSET  0xa8

#define LVX_JMPBUF_SIZE          0xb0

#endif /* _LVX_JMPBUF_H */
