libc_a_SOURCES += \
	%D%/memmove.S %D%/memmove-stub.c %D%/memset.S %D%/memcpy-asm.S %D%/memcpy.S %D%/strlen.c \
	%D%/strcpy.S %D%/strncpy.S %D%/memcmp.S %D%/strncmp.S %D%/strcmp.S %D%/setjmp.S %D%/ieeefp.c %D%/ffs.c
